// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, urlSearchParamsBodySerializer, formDataBodySerializer } from './client';
import type { SignUpAuthSignupPostData, SignUpAuthSignupPostResponse, SignUpAuthSignupPostError, LogInAuthLoginPostData, LogInAuthLoginPostResponse, LogInAuthLoginPostError, GetUserAuthSessionGetData, GetUserAuthSessionGetResponse, GetUserAuthSessionGetError, LogoutAuthLogoutGetData, LogoutAuthLogoutGetError, CreateFileFilesPostData, CreateFileFilesPostError, GetAllVideosVideosGetData, GetAllVideosVideosGetResponse, GetAllVideosVideosGetError, CreateVideoVideosPostData, CreateVideoVideosPostResponse, CreateVideoVideosPostError, GetVideoVideosVideoIdGetData, GetVideoVideosVideoIdGetResponse, GetVideoVideosVideoIdGetError, CreateAttemptVideosVideoIdAttemptsPostData, CreateAttemptVideosVideoIdAttemptsPostResponse, CreateAttemptVideosVideoIdAttemptsPostError, CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostData, CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostResponse, CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostError } from './types.gen';

export const client = createClient(createConfig());

/**
 * Sign Up
 */
export const signUpAuthSignupPost = <ThrowOnError extends boolean = false>(options: Options<SignUpAuthSignupPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<SignUpAuthSignupPostResponse, SignUpAuthSignupPostError, ThrowOnError>({
        url: '/auth/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Log In
 */
export const logInAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LogInAuthLoginPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogInAuthLoginPostResponse, LogInAuthLoginPostError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Get User
 */
export const getUserAuthSessionGet = <ThrowOnError extends boolean = false>(options?: Options<GetUserAuthSessionGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserAuthSessionGetResponse, GetUserAuthSessionGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/session',
        ...options
    });
};

/**
 * Logout
 */
export const logoutAuthLogoutGet = <ThrowOnError extends boolean = false>(options?: Options<LogoutAuthLogoutGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, LogoutAuthLogoutGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/logout',
        ...options
    });
};

/**
 * Create File
 */
export const createFileFilesPost = <ThrowOnError extends boolean = false>(options: Options<CreateFileFilesPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, CreateFileFilesPostError, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/files',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get All Videos
 */
export const getAllVideosVideosGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllVideosVideosGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllVideosVideosGetResponse, GetAllVideosVideosGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/videos/',
        ...options
    });
};

/**
 * Create Video
 */
export const createVideoVideosPost = <ThrowOnError extends boolean = false>(options: Options<CreateVideoVideosPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateVideoVideosPostResponse, CreateVideoVideosPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/videos/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Video
 */
export const getVideoVideosVideoIdGet = <ThrowOnError extends boolean = false>(options: Options<GetVideoVideosVideoIdGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVideoVideosVideoIdGetResponse, GetVideoVideosVideoIdGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/videos/{video_id}',
        ...options
    });
};

/**
 * Create Attempt
 */
export const createAttemptVideosVideoIdAttemptsPost = <ThrowOnError extends boolean = false>(options: Options<CreateAttemptVideosVideoIdAttemptsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateAttemptVideosVideoIdAttemptsPostResponse, CreateAttemptVideosVideoIdAttemptsPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/videos/{video_id}/attempts',
        ...options
    });
};

/**
 * Create Submission
 */
export const createSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPost = <ThrowOnError extends boolean = false>(options: Options<CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostResponse, CreateSubmissionVideosVideoIdAttemptsAttemptIdSubmissionsPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/videos/{video_id}/attempts/{attempt_id}/submissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};